version: '3'
# services:
#   flask_app:
#     image: ${IMAGE_NAME}
#     ports:
#       - "8000:8000"


services:
  discoveryservice:
    container_name: discoveryservice
    image: ${IMAGE_NAME}
    env_file:
      - .env
    ports:
      - "8000:8000"

    # environment:
    #   - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    #   - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    #   - EC2_USER=${EC2_USER}
    # volumes:
    #   - ../discoveryservice:/app/

# version: '3.8'
# services:
#   discoveryservice:
#     image: "${IMAGE_NAME}"  
#     ports:
#       - "8000:8000" 
#     volumes:
#       - ../discoveryservice:/app
    #working_dir: /app
    # command: python main.py