# version: '3'
# services:
#   flask_app:
#     image: ${IMAGE_NAME}
#     ports:
#       - "8000:8000"


services:
  discovery_service_container:
    image: ${IMAGE_NAME}
    ports:
      - '8000:8000'
    volumes:
      - ../discoveryservice:/app/