# version: '3'
# services:
#   flask_app:
#     image: ${IMAGE_NAME}
#     ports:
#       - "8000:8000"


# services:
#   discovery_service_container:
#     container_name: discoveryservice
#     image: ${IMAGE_NAME}
#     ports:
#       - '8000:8000'
#     volumes:
#       - ../discoveryservice:/app/

version: '3'
services:
  discovery_service_container:
    container_name: discoveryservice
    image: ${IMAGE_NAME}
    ports:
      - '8000:8000'
    volumes:
      - ../discoveryservice:/app
    #working_dir: /app
    # command: python main.py